### PR TITLE
Improve AWS detection

### PR DESCRIPTION
**Pull request by arossert**
To improve AWS detection I did 2 things

- Using `response.json(content_type=None)` - in some cases the metadata API returns Content-Type header of `text/plain` which cause this function to fail unless you tell it to ignore it.
- Checking `/sys/class/dmi/id/bios_vendor` file - added the ability to call `check_vendor_file` multiple time in the same `Provider` class.

### CODE REVIEW

**Comment by arossert** [comment]
@kshivakumar @dgzlopes This change is a bit bigger than I initially intended, if you have other ideas for implementation I will be happy to make the changes

**Comment by arossert** [comment]
@kshivakumar @dgzlopes Seems like I have the same issue on Windows machines, can you please review this change? 🙏

**Comment by arossert** [comment]
Currently I'm using this workaround

```
import aiohttp
from functools import partialmethod

aiohttp.ClientResponse.json = partialmethod(aiohttp.ClientResponse.json, content_type=None)
```

**Review by kshivakumar — COMMENTED** [review]
You could convert `vendor_file` to a tuple and make `check_vendor_file` iterate through each.
Passing an instance variable to a method seems pointless in this case.

**Comment by arossert** [comment]
@kshivakumar Thanks for reviewing, I was conflicted if doing this by converting the `vendor_file` to a iterable is better design 😃 
If you think it is better I can make the change.

**Comment by arossert** [comment]
I can also add the typo fix (#19) to this one

**Comment by arossert** [comment]
@kshivakumar @dgzlopes can you please review this one?

**Comment by arossert** [comment]
@dgzlopes Please, I need this fix for my project, can you review and merge 🙏

**Review by dgzlopes — APPROVED** [review]
Sorry for the delay :( 

Changes LGTM. Thanks for creating the PR! :heart:

**Comment by arossert** [comment]
Thanks for merging 💪🏻

**Pull request merged**
